version: '3.8'

services:
  web:
    build: ./services/odmf
    command: python3 /srv/start-odmf.py
    env_file:
      - .env
    volumes:
      - ./instance/:/srv/odmf/
    ports:
      - ${ODMF_PORT}:${ODMF_PORT}
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER:-db_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-db_passw}
      - POSTGRES_DB=${DB_NAME:-odmf}
volumes:
  postgres_data:

